routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PhoneBookController@index');

////vue-routes for understanding laravel system
//Route::get('/{name}', function (){
//    return redirect('/');
//})->where('name', '[A-Za-z]+');
Route::resource('phonebook', 'PhoneBookController');
Route::get('search', 'SearchController@search');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';
    public function phoneNums()
    {
        return $this->hasMany('App\Models\PhoneNum');
    }
}

app/Models/PhoneNum.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PhoneNum extends Model
{
    protected $table = 'phoneNums';
    protected $fillable = ['phone_num'];

    public function contact()
    {
        return $this->belongsTo('App\Models\Contact');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PhoneBookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Contact;
use App\Models\PhoneNum;
use App\services\PhoneNumeStoreHelper;

class PhoneBookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['contacts'] = Contact::all();
        return view('phonebook', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $phoneBook = new Contact;

        $phoneBook->name = $request->contact_name;
        $phoneBook->save();

        foreach ($request->phonenums as $key=>$number){
            $phoneNumber = new PhoneNum;
            $phoneNumber->contact_id = $phoneBook->id;
            $phoneNumber->phone_num = $number;
            $phoneNumber->save();
        }

       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contact  $phoneBook
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $phoneBook)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $phoneBook
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $phoneBook, $id)
    {
        $contact = Contact::find($id);
        return view('edit', ['contact'=>$contact]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $phoneBook
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $contact = Contact::find($id);
        $contact->name = $request->name;
        $contact->save();
        $phoneNumUpdate = new PhoneNumeStoreHelper();

        $phoneNumUpdate->phoneNumsSync($request, $id);

        return redirect('/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $phoneBook
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/PhoneNumsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PhoneNumsController extends Controller
{

}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Contact;
use App\Models\PhoneNum;

class SearchController extends Controller
{
    public function search(Request $request)
    {
        $result = [];
        $term = $request->term;
        $phoneNums = PhoneNum::where('phone_num', 'LIKE', '%'.$term.'%')->get();
        $contacts = Contact::where('name', 'LIKE', '%'.$term.'%')->get();
        if(count($contacts)>0){
            foreach ($contacts as $contact){
                $result = [$contact->name];
            }
        }
        if (count($phoneNums)>0){
            foreach ($phoneNums as $num){
                $result = ["$num->phone_num"];
            }
        }
        if(count($phoneNums) ===0 && count($contacts)===0){
            $result = ['Not matches for this request!'];
        }
        return $result;
    }
}

resources/views/edit.blade.php
@extends('layouts.main')
@section('content')
    <nav class="panel column is-offset-2 is-8">
        <form method="post" action="{{route('phonebook.update', $contact->id)}}">
            {{csrf_field()}}
            {{method_field('PUT')}}
            <p class="panel-heading">
                Contact {{$contact->name}} edit
            </p>

            <div class="field">
                <label class="label">Name</label>
                <div class="control has-icons-left has-icons-right">
                    <input class="input" name="name" type="text" placeholder="Text input" value="{{$contact->name}}">
                    <span class="icon is-small is-left">
                     <i class="fa fa-user"></i>
                </span>
                </div>
            </div>

            @foreach($contact->phoneNums as $num)
                <div class="field">
                    <label class="label">Phone number</label>
                    <div class="control panel-block has-icons-left has-icons-right ">
                        <input class="input phone_field column is-10" name="phonenums[]" type="text" value="{{$num->phone_num}}">
                        <span class="icon is-small is-left">
                            <i class="fa fa-phone"></i>
                        </span>
                        <button class="panel-icon item-delete column is-2">
                            <i class="has-text-danger fa fa-trash"></i>
                        </button>
                    </div>
                </div>
            @endforeach

            <div class="new-phone-nums"></div>
            <div id="num_add"><img class="add_phone_num"></div>
            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-link">Submit</button>
                </div>
                <div class="control">
                    <button class="button is-text">Cancel</button>
                </div>
            </div>
        </form>
    </nav>
@endsection

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery-ui.min.css')}}">
    <title>Document</title>
</head>
<body>
<div class="container">
    @yield('content')
</div>
<script src="{{asset('js/app.js')}}"></script>
</body>
</html>

resources/views/phonebook.blade.php
@extends('layouts.main')
@section('content')
    <nav class="panel column is-offset-2 is-8">
        <p class="panel-heading">
            Phone book
            <button id="add_contact" class="button is-link is-outlined">
                Add contact
            </button>
        </p>
        <div class="panel-block">
            <p class="column is-7"></p>
            <p class="control has-icons-left column is-5">
                <input class="input is-small" type="text" id="searchContact" name="searchContact" placeholder="search">

            </p>
        </div>

        @if($contacts->count()>0)
            @foreach($contacts as $contact)

        <div class="panel-block">
            <span class="column is-5">
                {{$contact->name}}
            </span>
            <span class="column is-5">
                <p>Phones: </p>
                <div class="select">
                  <select>
                      @foreach($contact->phoneNums as $num)
                    <option>{{$num->phone_num}}</option>
                      @endforeach
                  </select>
                </div>
            </span>
            <a href="{{route('phonebook.edit', $contact->id)}}"  class="panel-icon column is-1">
                    <i class="has-text-info fa fa-edit"></i>
            </a>
            <a href="" class="panel-icon column is-1"
               title="Delete this post" onclick="
                    if(confirm('Are you sure you want to delete this contact?'))
                    {
                    event.preventDefault(); document.getElementById('delete-form-{{$contact->id}}').submit()
                    }">
                <i class="has-text-danger fa fa-trash"></i>
            </a>
            <form action="{{route('phonebook.destroy', $contact->id)}}" method="post" id="delete-form-{{$contact->id}}" style="display: none">
                {{csrf_field()}}
                {{method_field('DELETE')}}
            </form>
        </div>
            @endforeach
         @endif
    </nav>
    <div class="modal">
        <div class="modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">Add new contact</p>
                <button id="close_modal" class="delete" aria-label="close"></button>
            </header>
            <section class="modal-card-body">
                <form action="/phonebook" method="post" id="new_contact_form">
                    {{csrf_field()}}
                    <div class="field">
                        <label class="label">Name</label>
                        <div class="control">
                            <input class="input contact_name" type="text" name="contact_name" placeholder="Contact name" required>
                            <span id="name_error"></span>
                        </div>
                            <p class="help">Enter contact name</p>
                    </div>
                    <div class="field">
                        <label class="label">Phone</label>
                        <div class="control">
                            <input class="input phone_field contact_phone" type="text" name="phonenums[]" placeholder="Phone number" required>
                            <span id="phone_error"></span>
                        </div>
                        <p class="help">Enter contact phone number</p>
                    </div>
                    <div class="new-phone-nums"></div>
                </form>
                <div id="num_add"><img class="add_phone_num"></div>
            </section>
            <footer class="modal-card-foot">
                <button class="button is-success" id="new_contact_success">Save contact</button>
                <button id="cancel" class="button">Cancel</button>
            </footer>
        </div>
    </div>

@stop